=== CheeJustin/winter2015-lab06/data/bonanza.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Order placement data for Barker Bob's Burger Bar's Bigger, Better Burger Bonzanza
-->

<!-- An order identifies the customer, order type, burgers, and anything special -->
<!ELEMENT order (customer, delivery?, burger+, special?)>

<!-- A customer is identified simply by their name -->
<!ELEMENT customer (#PCDATA)>

<!-- An order can be for eat-in, takeout, or delivery ... customer-specified -->
<!ATTLIST order
    type    (eatin|takeout|delivery) #REQUIRED
>

<!-- An order to be delivered will need delivery instructions -->
<!ELEMENT delivery (#PCDATA)>

<!-- Let's provide for any special instructions -->
<!ELEMENT special (#PCDATA)>

<!-- The burgers will be specified individually
Burger customization...
- 1 of 5 patty types
- up to 2 cheeses
- any number of toppings
- any number of sauces
- special instructions
- an optional name, should the customer wish to propose this as a meny item
 -->
<!ELEMENT burger (patty, cheese?, topping*, sauce*, instructions?, name?)>

<!-- A patty can be one of five types, (assume beef), and might be named explicitly -->
<!ELEMENT patty (#PCDATA)>
<!ATTLIST patty
    type    (beef|pork|turkey|bison|vege) "beef"
>

<!-- The customer can order two cheeses. Let's assume that one might go on top
and one on bottom, and provide for unique codes for these. -->
<!ELEMENT cheese EMPTY>
<!ATTLIST cheese
    top     (american|swiss|jack|blue|gruyere|gouda|aged|goat|brie) #IMPLIED
    bottom  (american|swiss|jack|blue|gruyere|gouda|aged|goat|brie) #IMPLIED
>

<!-- Toppings... there could be tones, so we'll handle them individually -->
<!ELEMENT topping (#PCDATA)>
<!ATTLIST topping
    type    (lettuce|tomato|raw|dill|roasted|shrooms|salsa|bacon|chili|fkchili|avacado|egg|porkbelly) #REQUIRED
>

<!-- Sauces are similar to toppings -->
<!ELEMENT sauce (#PCDATA)>
<!ATTLIST sauce
    type    (ketchup|mustard|mayo|fksauce) #REQUIRED
>

<!-- Instructions can be literally anything -->
<!ELEMENT instructions (#PCDATA)>

<!-- A name can be anything for now - we'll validate later -->
<!ELEMENT name (#PCDATA)>

=== CheeJustin/winter2015-lab06/data/order3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE order SYSTEM 'bonanza.dtd'>

<order type="takeout">
    <customer>Justin</customer>
    <burger>
        <patty type="bison"/>
        <cheese top="gouda" bottom="brie"/>
        <topping type="bacon"/>
        <topping type="avacado"/>
        <topping type="lettuce"/>
        <sauce type="ketchup"/>
        <sauce type="mayo"/>
        <instructions>smear peanut butter on the inside of each bun</instructions>
    </burger>
    <burger>
        <patty type="turkey"/>
        <cheese top="goat" bottom="jack"/>
        <topping type="fkchili"/>
        <topping type="avacado"/>
        <topping type="lettuce"/>
        <topping type="dill"/>
        <topping type="raw"/>
        <sauce type="fksauce"/>
        <sauce type="mustard"/>
        <instructions>douse in maple syrup</instructions>
    </burger>
</order>
